#!/usr/bin/with-contenv bash

# if this is a legacy container do not run any logic
[[ -d /config/www/tt-rss ]] && \
	exit 0

# create symlinks
symlinks=( \
/var/www/html/themes.local \
/var/www/html/plugins.local \
/var/www/html/cache \
/var/www/html/lock \
/var/www/html/feed-icons
)

for i in "${symlinks[@]}"; do
	[[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]] && \
		rm -Rf "$i" && \
		ln -s /config/"$(basename "$i")" "$i"
	[[ -e "$i" && ! -L "$i" ]] && \
		mv "$i" /config/"$(basename "$i")" && \
		ln -s /config/"$(basename "$i")" "$i"
done

# config.php file setup
if [ "${DB_TYPE+x}" ]; then
    echo "DB_TYPE set, injecting env variables into config.php"
    echo "Creating config.php from the dist file"
    cp /var/www/html/config.php-dist /config/config.php
    ln -s /config/config.php /var/www/html/config.php
    [[ "${DB_TYPE+x}" ]] && echo -e "putenv('TTRSS_DB_TYPE=$DB_TYPE');" >> /config/config.php
    [[ "${DB_HOST+x}" ]] && echo -e "putenv('TTRSS_DB_HOST=$DB_HOST');" >> /config/config.php
    [[ "${DB_USER+x}" ]] && echo -e "putenv('TTRSS_DB_USER=$DB_USER');" >> /config/config.php
    [[ "${DB_NAME+x}" ]] && echo -e "putenv('TTRSS_DB_NAME=$DB_NAME');" >> /config/config.php
    [[ "${DB_PASS+x}" ]] && echo -e "putenv('TTRSS_DB_PASS=$DB_PASS');" >> /config/config.php
    [[ "${DB_PORT+x}" ]] && echo -e "putenv('TTRSS_DB_PORT=$DB_PORT');" >> /config/config.php
    [[ "${MYSQL_CHARSET+x}" ]] && echo -e "putenv('TTRSS_MYSQL_CHARSET=$MYSQL_CHARSET');" >> /config/config.php
    [[ "${SELF_URL_PATH+x}" ]] && echo -e "putenv('TTRSS_SELF_URL_PATH=$SELF_URL_PATH');" >> /config/config.php
    [[ "${SINGLE_USER_MODE+x}" ]] && echo -e "putenv('TTRSS_SINGLE_USER_MODE', $SINGLE_USER_MODE);" >> /config/config.php
    [[ "${SIMPLE_UPDATE_MODE+x}" ]] && echo -e "putenv('TTRSS_SIMPLE_UPDATE_MODE', $SIMPLE_UPDATE_MODE);" >> /config/config.php
    [[ "${PHP_EXECUTABLE+x}" ]] && echo -e "putenv('TTRSS_PHP_EXECUTABLE=$PHP_EXECUTABLE');" >> /config/config.php
    [[ "${LOCK_DIRECTORY+x}" ]] && echo -e "putenv('TTRSS_LOCK_DIRECTORY=$LOCK_DIRECTORY');" >> /config/config.php
    [[ "${CACHE_DIR+x}" ]] && echo -e "putenv('TTRSS_CACHE_DIR=$CACHE_DIR');" >> /config/config.php
    [[ "${ICONS_DIR+x}" ]] && echo -e "putenv('TTRSS_ICONS_DIR=$ICONS_DIR');" >> /config/config.php
    [[ "${ICONS_URL+x}" ]] && echo -e "putenv('TTRSS_ICONS_URL=$ICONS_URL');" >> /config/config.php
    [[ "${AUTH_AUTO_CREATE+x}" ]] && echo -e "putenv('TTRSS_AUTH_AUTO_CREATE', $AUTH_AUTO_CREATE);" >> /config/config.php
    [[ "${AUTH_AUTO_LOGIN+x}" ]] && echo -e "putenv('TTRSS_AUTH_AUTO_LOGIN', $AUTH_AUTO_LOGIN);" >> /config/config.php
    [[ "${FORCE_ARTICLE_PURGE+x}" ]] && echo -e "putenv('TTRSS_FORCE_ARTICLE_PURGE=$FORCE_ARTICLE_PURGE');" >> /config/config.php
    [[ "${SPHINX_SERVER+x}" ]] && echo -e "putenv('TTRSS_SPHINX_SERVER=$SPHINX_SERVER');" >> /config/config.php
    [[ "${SPHINX_INDEX+x}" ]] && echo -e "putenv('TTRSS_SPHINX_INDEX=$SPHINX_INDEX');" >> /config/config.php
    [[ "${ENABLE_REGISTRATION+x}" ]] && echo -e "putenv('TTRSS_ENABLE_REGISTRATION', $ENABLE_REGISTRATION);" >> /config/config.php
    [[ "${REG_NOTIFY_ADDRESS+x}" ]] && echo -e "putenv('TTRSS_REG_NOTIFY_ADDRESS=$REG_NOTIFY_ADDRESS');" >> /config/config.php
    [[ "${REG_MAX_USERS+x}" ]] && echo -e "putenv('TTRSS_REG_MAX_USERS=$REG_MAX_USERS');" >> /config/config.php
    [[ "${SESSION_COOKIE_LIFETIME+x}" ]] && echo -e "putenv('TTRSS_SESSION_COOKIE_LIFETIME=$SESSION_COOKIE_LIFETIME');" >> /config/config.php
    [[ "${SMTP_FROM_NAME+x}" ]] && echo -e "putenv('TTRSS_SMTP_FROM_NAME=$SMTP_FROM_NAME');" >> /config/config.php
    [[ "${SMTP_FROM_ADDRESS+x}" ]] && echo -e "putenv('TTRSS_SMTP_FROM_ADDRESS=$SMTP_FROM_ADDRESS');" >> /config/config.php
    [[ "${DIGEST_SUBJECT+x}" ]] && echo -e "putenv('TTRSS_DIGEST_SUBJECT=$DIGEST_SUBJECT');" >> /config/config.php
    [[ "${CHECK_FOR_UPDATES+x}" ]] && echo -e "putenv('TTRSS_CHECK_FOR_UPDATES', $CHECK_FOR_UPDATES);" >> /config/config.php
    [[ "${ENABLE_GZIP_OUTPUT+x}" ]] && echo -e "putenv('TTRSS_ENABLE_GZIP_OUTPUT', $ENABLE_GZIP_OUTPUT);" >> /config/config.php
    [[ "${PLUGINS+x}" ]] && echo -e "putenv('TTRSS_PLUGINS=$PLUGINS');" >> /config/config.php
    [[ "${LOG_DESTINATION+x}" ]] && echo -e "putenv('TTRSS_LOG_DESTINATION=$LOG_DESTINATION');" >> /config/config.php
fi

# permissions
chown -R abc:abc \
	/config \
	/var/www/html/
